version: '3.7'

networks:
  ps_system_network:
 
services:
  ps_application:
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    container_name: ps_application
    build:
      context: .
      dockerfile: Application/Dockerfile
    networks:
        - ps_system_network
