version: '3.7'

networks:
  ps_system_network:
 
services:
  ps_application:
    image: 408581281203.dkr.ecr.eu-central-1.amazonaws.com/privatni-smjestaj
    container_name: ps_application
    build:
      context: .
      dockerfile: Application/Dockerfile
    networks:
        - ps_system_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000